export const USER_SET_LANGUAGE = 'USER_SET_LANGUAGE';
export const PUSH_NOTIFICATION_SETTINGS = 'PUSH_NOTIFICATION_SETTINGS';
export const USER_INFORMATION = 'USER_INFORMATION';
export const CURRENT_VEHICLE = 'CURRENT_VEHICLE';
export const USER_ID = 'USER_ID';
